/**
 * constants.js - 消息类型常量定义
 * 
 * 服务端与客户端通信的消息类型协议
 */

// 服务端发送的消息类型
export const ServerMsgType = {
    BATTLE_LIST: "BATTLE_LIST",
    INIT_STATE: "INIT_STATE",
    UPDATE_HP: "UPDATE_HP",
    UPDATE_MP: "UPDATE_MP",
    UPDATE_EFFECTS: "UPDATE_EFFECTS",
    UNIT_DIED: "UNIT_DIED",
    LOG: "LOG",
    TURN_START: "TURN_START",
    DAMAGE: "DAMAGE",
    HEAL: "HEAL",
    EFFECT_APPLIED: "EFFECT_APPLIED",
    EFFECT_REMOVED: "EFFECT_REMOVED",
    BATTLE_END: "BATTLE_END",
    RETURN_TO_MENU: "RETURN_TO_MENU",
    REQUEST_ACTION: "REQUEST_ACTION",
    REQUEST_SKILL: "REQUEST_SKILL",
    REQUEST_TARGET: "REQUEST_TARGET"
};

// 客户端发送的消息类型
export const ClientMsgType = {
    GET_BATTLES: "GET_BATTLES",
    START_BATTLE: "START_BATTLE",
    SELECT_CATEGORY: "SELECT_CATEGORY",
    SELECT_SKILL: "SELECT_SKILL",
    SELECT_TARGET: "SELECT_TARGET",
    RESTART: "RESTART",
    RETURN_TO_MENU: "RETURN_TO_MENU"
};
